language: java
services:
        - docker
script:
        - ./inject_creds.sh
        - ./mvnw package
        - ./mvnw sonar:sonar -Dsonar.projectKey=GardenShare -Dsonar.organization=gardenshare -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY
        - docker build . -e DB_PASSWORD="$DB_PASSWORD" -t fuckthisshituo/garden-share:latest
        - docker login -u fuckthisshituo -p $DOCKER_PASS
        - docker push fuckthisshituo/garden-share:latest
notifications:
        slack: csc307group:r3whK2mx6xWyRs1UhXkuOFk5
